AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  CICDApiGatewayPreTestFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: cicdTestJava
      Handler: com.amazonaws.lambda.GetDistributorsList::handleRequest
      Runtime: java.8
      Environment:
        Variables: 
          S3_BUCKET: cicdsample.appcohesion.io



     

